using Microsoft.EntityFrameworkCore.Migrations;
namespace Leads.Infrastructure.Persistence.Migrations;
public partial class Initial : Migration
{
 protected override void Up(MigrationBuilder m)
 {
  m.Sql(@"CREATE SCHEMA IF NOT EXISTS leads;
CREATE TABLE IF NOT EXISTS leads.customers (customer_id uuid PRIMARY KEY, empresa_id bigint NOT NULL, nombre varchar(250) NOT NULL, telefono_normalizado varchar(100), email_normalizado varchar(250), ciudad varchar(150));
CREATE INDEX IF NOT EXISTS ix_customers_empresa_telefono ON leads.customers(empresa_id, telefono_normalizado);
CREATE INDEX IF NOT EXISTS ix_customers_empresa_email ON leads.customers(empresa_id, email_normalizado);
CREATE TABLE IF NOT EXISTS leads.leads (lead_id bigint PRIMARY KEY, fecha_registro timestamptz NOT NULL, canal varchar(50) NOT NULL, empresa_id bigint NOT NULL, punto_venta_id bigint NOT NULL, nombre_cliente varchar(250) NOT NULL, telefono varchar(100), email varchar(250), ciudad varchar(150), modelo_interes_texto varchar(250), estado_gestion varchar(30) NOT NULL, fecha_primer_contacto timestamptz, campania varchar(250), customer_id uuid NULL REFERENCES leads.customers(customer_id), telefono_normalizado varchar(100), email_normalizado varchar(250), ciudad_normalizada varchar(150), canal_normalizado varchar(50), modelo_texto_normalizado varchar(250), motorcycle_sku varchar(100), model_match_confidence numeric(5,4), model_match_method varchar(30));
CREATE INDEX IF NOT EXISTS ix_leads_empresa_punto ON leads.leads(empresa_id,punto_venta_id);
CREATE INDEX IF NOT EXISTS ix_leads_fecha ON leads.leads(fecha_registro);
CREATE INDEX IF NOT EXISTS ix_leads_motorcycle_sku ON leads.leads(motorcycle_sku);
CREATE TABLE IF NOT EXISTS leads.motorcycles (sku varchar(100) PRIMARY KEY, marca varchar(100) NOT NULL, linea varchar(150) NOT NULL, cilindraje integer NOT NULL, segmento varchar(100) NOT NULL, precio_lista numeric(18,2) NOT NULL, puntos_venta_disponibles integer NOT NULL, unidades_disponibles integer NOT NULL);
CREATE INDEX IF NOT EXISTS ix_motorcycles_marca_linea ON leads.motorcycles(marca,linea);
CREATE TABLE IF NOT EXISTS leads.advisors (asesor_id bigint PRIMARY KEY, nombre varchar(250) NOT NULL, punto_venta_id bigint NOT NULL, empresa_id bigint NOT NULL, capacidad_diaria_leads integer NOT NULL, activo boolean NOT NULL, fecha_ingreso timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS ix_advisors_empresa_punto_activo ON leads.advisors(empresa_id,punto_venta_id,activo);
CREATE TABLE IF NOT EXISTS leads.conversations (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, conversacion_id varchar(150) NOT NULL UNIQUE, lead_id bigint NOT NULL REFERENCES leads.leads(lead_id), canal varchar(50) NOT NULL, fecha_inicio timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS ix_conversations_lead ON leads.conversations(lead_id);
CREATE TABLE IF NOT EXISTS leads.messages (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, conversation_id bigint NOT NULL REFERENCES leads.conversations(id), sender_type varchar(30) NOT NULL, content text NOT NULL, sent_at timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS ix_messages_conversation ON leads.messages(conversation_id);
CREATE TABLE IF NOT EXISTS leads.lead_enrichments (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, lead_id bigint NOT NULL REFERENCES leads.leads(lead_id), modelo_interes varchar(250), cuota_inicial numeric(18,2), forma_pago varchar(100), intencion varchar(100), objecion varchar(500), solicito_cita boolean NOT NULL, solicito_cotizacion boolean NOT NULL, confianza numeric(5,4) NOT NULL, provider varchar(100) NOT NULL, pipeline_version varchar(100) NOT NULL, created_at timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS ix_enrichment_lead_created ON leads.lead_enrichments(lead_id,created_at);
CREATE TABLE IF NOT EXISTS leads.lead_scores (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, lead_id bigint NOT NULL REFERENCES leads.leads(lead_id), historical_probability numeric(5,4) NOT NULL, final_score numeric(5,4) NOT NULL, priority varchar(20) NOT NULL, reasons_json text NOT NULL, model_version varchar(100) NOT NULL, created_at timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS ix_scores_lead_created ON leads.lead_scores(lead_id,created_at);
CREATE TABLE IF NOT EXISTS leads.lead_assignments (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, lead_id bigint NOT NULL REFERENCES leads.leads(lead_id), asesor_id bigint NOT NULL REFERENCES leads.advisors(asesor_id), assigned_at timestamptz NOT NULL, reason varchar(500) NOT NULL);
CREATE INDEX IF NOT EXISTS ix_assignments_lead_created ON leads.lead_assignments(lead_id,assigned_at);
CREATE TABLE IF NOT EXISTS leads.pipeline_runs (run_id uuid PRIMARY KEY, status varchar(30) NOT NULL, pipeline_version varchar(100) NOT NULL, started_at timestamptz NOT NULL, finished_at timestamptz NULL, records_read integer NOT NULL DEFAULT 0, records_processed integer NOT NULL DEFAULT 0, records_failed integer NOT NULL DEFAULT 0, summary_json text NULL, error text NULL);
CREATE INDEX IF NOT EXISTS ix_pipeline_runs_started ON leads.pipeline_runs(started_at); ");;
 }
 protected override void Down(MigrationBuilder m){m.Sql("DROP SCHEMA IF EXISTS leads CASCADE;");}
}
