// <auto-generated />
using System;
using Leads.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Leads.Infrastructure.Migrations
{
    [DbContext(typeof(LeadsDbContext))]
    partial class LeadsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("leads")
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Leads.Domain.Entities.Advisor", b =>
                {
                    b.Property<long>("AsesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AsesorId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CapacidadDiariaLeads")
                        .HasColumnType("integer");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<long>("PuntoVentaId")
                        .HasColumnType("bigint");

                    b.HasKey("AsesorId");

                    b.HasIndex("EmpresaId", "PuntoVentaId", "Activo");

                    b.ToTable("advisors", "leads");
                });

            modelBuilder.Entity("Leads.Domain.Entities.Conversation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConversacionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LeadId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConversacionId")
                        .IsUnique();

                    b.HasIndex("LeadId");

                    b.ToTable("conversations", "leads");
                });

            modelBuilder.Entity("Leads.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<string>("EmailNormalizado")
                        .HasColumnType("text");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("TelefonoNormalizado")
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.HasIndex("EmpresaId", "EmailNormalizado");

                    b.HasIndex("EmpresaId", "TelefonoNormalizado");

                    b.ToTable("customers", "leads");
                });

            modelBuilder.Entity("Leads.Domain.Entities.Lead", b =>
                {
                    b.Property<long>("LeadId")
                        .HasColumnType("bigint");

                    b.Property<string>("Campania")
                        .HasColumnType("text");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CanalNormalizado")
                        .HasColumnType("text");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<string>("CiudadNormalizada")
                        .HasColumnType("text");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmailNormalizado")
                        .HasColumnType("text");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<string>("EstadoGestion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FechaPrimerContacto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ModelMatchConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("ModelMatchMethod")
                        .HasColumnType("text");

                    b.Property<string>("ModeloInteresTexto")
                        .HasColumnType("text");

                    b.Property<string>("ModeloTextoNormalizado")
                        .HasColumnType("text");

                    b.Property<string>("MotorcycleSku")
                        .HasColumnType("text");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<long>("PuntoVentaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("TelefonoNormalizado")
                        .HasColumnType("text");

                    b.HasKey("LeadId");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("MotorcycleSku");

                    b.HasIndex("EmpresaId", "PuntoVentaId");

                    b.ToTable("leads", "leads");
                });

            modelBuilder.Entity("Leads.Domain.Entities.LeadAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AsesorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LeadId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeadId", "AssignedAt");

                    b.ToTable("lead_assignments", "leads");
                });

            modelBuilder.Entity("Leads.Domain.Entities.LeadEnrichment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Confianza")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CuotaInicial")
                        .HasColumnType("numeric");

                    b.Property<string>("FormaPago")
                        .HasColumnType("text");

                    b.Property<string>("Intencion")
                        .HasColumnType("text");

                    b.Property<long>("LeadId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModeloInteres")
                        .HasColumnType("text");

                    b.Property<string>("Objecion")
                        .HasColumnType("text");

                    b.Property<string>("PipelineVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SolicitoCita")
                        .HasColumnType("boolean");

                    b.Property<bool>("SolicitoCotizacion")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("LeadId", "CreatedAt");

                    b.ToTable("lead_enrichments", "leads");
                });

            modelBuilder.Entity("Leads.Domain.Entities.LeadScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FinalScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("HistoricalProbability")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<long>("LeadId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ReasonsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeadId", "CreatedAt");

                    b.ToTable("lead_scores", "leads");
                });

            modelBuilder.Entity("Leads.Domain.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("messages", "leads");
                });

            modelBuilder.Entity("Leads.Domain.Entities.Motorcycle", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.Property<int>("Cilindraje")
                        .HasColumnType("integer");

                    b.Property<string>("Linea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioLista")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PuntosVentaDisponibles")
                        .HasColumnType("integer");

                    b.Property<string>("Segmento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnidadesDisponibles")
                        .HasColumnType("integer");

                    b.HasKey("Sku");

                    b.HasIndex("Marca", "Linea");

                    b.ToTable("motorcycles", "leads");
                });

            modelBuilder.Entity("Leads.Domain.Entities.PipelineRun", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PipelineVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RecordsFailed")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsRead")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SummaryJson")
                        .HasColumnType("text");

                    b.HasKey("RunId");

                    b.HasIndex("StartedAt");

                    b.ToTable("pipeline_runs", "leads");
                });
#pragma warning restore 612, 618
        }
    }
}
